version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - python -m pip install .

sphinx:
  configuration: docs/conf.py
  builder: "dirhtml"

formats:
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
  