name: Automated testing

on: push

env:
  FORCE_COLOR: 1
  MYPY_FORCE_COLOR: 1
  GEOCOMPY_TEST_PORT_CLIENT: /tmp/geocompy_pty_client
  GEOCOMPY_TEST_PORT_SERVER: /tmp/geocompy_pty_server

jobs:
  testing:
    name: Running tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Setup virtual serial port
        run: |
          sudo apt install socat
          socat pty,raw,echo=0,link=$GEOCOMPY_TEST_PORT_CLIENT pty,raw,echo=0,link=$GEOCOMPY_TEST_PORT_SERVER &
          export GEOCOMPY_TEST_PTY=$!

          python tests/com_echo_server.py &
          export GEOCOMPY_TEST_ECHOSERVER=$!
        
      - name: Build and install package
        run: python -m pip install .

      - name: Test with pytest
        run: |
          python -m pip install --upgrade pip
          python -m pip install --group testing
          python -m pytest
      
      - name: Kill echo echo server
        run: |
          kill $GEOCOMPY_TEST_ECHOSERVER
          kill $GEOCOMPY_TEST_PTY
  
  linting:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tool: ["flake8", "mypy"]
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
        
      - name: Build and install package
        run: python -m pip install .

      - name: Running ${{ matrix.tool }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install --group linting
          python -c "print('=========== ${{ matrix.tool }} ===========')"
          python -m ${{ matrix.tool }} src/ tests/
